import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import axios from 'axios';

export default function Home({ weather }) {
  const [zipcode, setZipcode] = useState('');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <body className='bg-gray-900'> */}
      <form className='flex flex-col mx-auto min-h-[100vh] justify-center appearance-none -py-20 bg-gray-900'>
        <div id='logo' className='my-4 flex mx-auto'>
          <svg
            xmlns='http://www.w3.org/2000/svg'
            className='h-16 w-16 text-yellow-300'
            fill='none'
            viewBox='0 0 24 24'
            stroke='currentColor'
          >
            <path
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth={2}
              d='M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z'
            />
          </svg>
          <h1 className='ml-1 flex items-center font-bold text-4xl text-white'>
            WeatherBuddy
          </h1>
        </div>
        <input
          className='border border-gray-700 rounded-full p-3 m-0 bg-gray-900 text-white w-4/5 mx-auto'
          type='text'
          name='zipcode'
          id='zipcode'
          maxLength='5'
          minLength='5'
          placeholder='Enter Zipcode - Ex: 35976'
          onChange={(e) => setZipcode(e.target.value)}
        />
        <Link href={`/zipcode/${zipcode}`}>
          <a className='p-2 bg-gray-800 w-2/4 mx-auto my-6 text-center text-white'>
            Search
          </a>
        </Link>
      </form>
      {/* </body> */}
      {/* {daily.map(({ dt }) => (
        <>
          <p className=''>{new Date(dt * 1000).toDateString()}</p>
        </>
      ))} */}
      {/* <pre>{JSON.stringify(weather.daily, null, 2)}</pre> */}
    </>
  );
}

export const getStaticProps = async () => {
  const { data: guntersville } = await axios.get(
    `https://api.openweathermap.org/data/2.5/onecall?lat=34.3582&lon=-86.2947&units=imperial&exclude=current,minutely,hourly&appid=${process.env.NEXT_PUBLIC_OPENWEATHERMAP_API_KEY}`
  );

  // console.log(weather);
  return {
    props: {
      weather: guntersville,
    },
  };
};
